### ISSUE TITLE
[Bug] Japscan: impossible to get chapters

### ISSUE THREAD

**Issue by dryx01** [inorichi/tachiyomi-extensions#2535]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. Go to an chapter on japscan source (it happen with "a ranker who lives a second time" and "the second coming of gluttony" for example)
2. Try to read it

### Actual behavior
Sometimes it's work, but for mostly manga the reading and downloading function failed.
A screenshot here:
![Screenshot_20200329-000623](https://user-images.githubusercontent.com/6872170/77836068-267a6080-7153-11ea-9fac-080ab188f129.jpg)

### Other details
I tried to wipe cache, cookies, change IP, change DNS, not working at all.
I specify that it's working on website.

**Comment by dryx01** [comment]
If you found a method for debugging extension please say it, it'll be faster.

**Comment by morcefaster** [comment]
Looks like they're using a new format on the web which is like a webtoon reader. Maybe that's what's breaking it.

**Comment by dryx01** [comment]
> Looks like they're using a new format on the web which is like a webtoon reader. Maybe that's what's breaking it.

Yes after test it's effectively that. Only webtoons have problem.

**Comment by DrkThunder** [comment]
Hello, i've a same problem but it's for every reader

**Comment by DiogoVieiraFerreira** [comment]
I've test with : 

not working : 
- A Returner's Magic Should Be Special
- DaXiangWuXing (Taoist)
- The Gamer
- The Legendary Moonlight Sculptor

working :
- Combat Continent - Douluo Dalu
- Tian Can Tu Dou
- Doupo Cangqiong
- Hunter Age
- Into The Net
- solo leveling
- Tales Of Demons And Gods

i don't know what's a difference between the next webtoon.. but some one don't work

**Comment by o01210o** [comment]
Seems that they removed the scrambler o_o
https://www.japscan.co/manga/eden-s-zero/
[chapter 89 is scrambled](https://i.imgur.com/2Jhk71K.png) -----  [90 isn't](https://i.imgur.com/1lGR5p3.png) (released yesterday)

**Japscan usually scrambled the chapters of mangas that they bought the official french simulpub version** (like Eden's Zero)

I've searched for another manga and it's also the case of https://www.japscan.co/manga/fuuka/ (chapter 175 is scrambled and 176 isn't)

Maybe it has something to do with that issue?

**Comment by yreb** [comment]
The problem appears also inside chapters, you can see it, if you use the download function

- On some chapter you can reach 80% of the file,
- on other 0%
- sometimes , 100% of the chapter is avaliable

**Comment by maximehua** [comment]
So ? How can it be solved ?

**Comment by Hart-JV** [comment]
Is there any method/solution given for the problem? I'm not sure to undrerstand everything.

**Comment by Hart-JV** [comment]
Allow me to explain my issue in french😅😅
Le problème c'est qu'en ce moment aucun de ceux de Tachiyomi ne fonctionne. Certains de ceux de Tachiyomi version Device fonctionnent encore notamment Vampire Knight. Par contre Rosario Vampire II ne fonctionne ni dans l'un ni dans l'autre. Et c'est arrivé tout à coup comme ça alors que je finissais de lire le tome 6😮😮

**Comment by Rediowz** [comment]
The issue doesn't only happen with webtoons, it happens with everything (Boku no Hero Academia for example)

**Comment by Lyoses** [comment]
It doesn't work for me either, suddenly it stopped working, for my part it was prison school that stopped working (and all the others after) Still no solution?

**Comment by sam5558** [comment]
It stopped working for me also.

On desktop, i'm using hakuneko to download from various sources. among them is japscan, which is working. The only glitch is that i have to setup a relatively big timeout for it to keep downloading from japscan.... 

Maybe it's interesting to see how they're dealing with these recurrent japscan issues : https://github.com/manga-download/hakuneko/issues?q=is%3Aissue+is%3Aopen+japscan

**Comment by dryx01** [comment]
I found that chapters doesn't load on the webview, when firefox or chrome load it successfuly. Perhaps Japscan detect the browser used and act accordingly.
Exemple with a screenshot:
![Screenshot_20200524-001924](https://user-images.githubusercontent.com/6872170/82824633-f4168680-9ea9-11ea-964d-28f8ea301e48.jpg)

**Comment by AlCiavi** [comment]
Same for me. It works, then suddenly it doesn't work. I hope you guys will find a solution to this issue, because we french only have this source to read anything

**Comment by AbdullahM0hamed** [comment]
Well - you'll probably want to recommend better sources, then. 
> we French only have this source to read anything

**Comment by AlCiavi** [comment]
> Well - you'll probably want to request better sources, then.
> 
> > we French only have this source to read anything

Unfortunately not. That's why I hope someone will come up with a solution

**Comment by AbdullahM0hamed** [comment]
Unfortunately not? Do you mean better sources simply don't exist?

**Comment by AlCiavi** [comment]
> Unfortunately not? Do you mean better sites simply don't exist?

Not to my knowledge. I only know Scantrad but it never worked on Tachiyomi

**Comment by dryx01** [comment]
> Unfortunately not? Do you mean better sites simply don't exist?

Japscan is unfortunaly the biggest aggregator of french sources. The website is full of ad and it don't mention the translator.
I hope that someone can somehow find a solution 😓

**Comment by ZINGGGGGGGGGG** [comment]
Any solution or alternative ?

**Comment by Mitia99** [comment]
@ZINGGGGGGGGGG 
Mangakawaii/Scan VF,Scan OP in CMS extension are also a great database

**Comment by Astroop** [comment]
Same problem here :(
Unfortunately, Mangakawaii and other French sources referenced in tachiyomi only give access to a few chapters but rarely the whole mangas...

**Comment by Mitia99** [comment]
Up

**Comment by Ooggle** [comment]
Still got the problem, perhaps it can be fixed by changing the user-agent used to made the request? It's clear that webpages doesn't provide the chapter images under some circumstances. They probably want to block automatic pages donwload by checking that the request has been made by a legit browser.
Maybe it can also be a JavaScript challenge?

**Comment by LeavesEatingCow** [comment]
Has the problem been fixed in the latest version? If not, which other apps do not have this problem?

**Comment by Mitia99** [comment]
@LeavesEatingCow 
The problem is still present on japscan ver1.2.20

**Comment by Mitia99** [comment]
@LeavesEatingCow The problem is still present on Japscan ver1.2.20
Manga tested:ah my goddess (chap 307)

**Comment by Bamaraj09** [comment]
I hope that the problem will be solved quickly. It's already been a few months since we can no longer read manga on tachiyomi.

**Comment by Mitia99** [comment]
Additional information:

![Japscan.png](https://user-images.githubusercontent.com/56766778/90364762-f0d40680-e064-11ea-83db-a3998349b4a3.png)Mi Manga Nu app(  https://github.com/raulhaag/MiMangaNu ) loads chapter but they are broken

**Comment by LeavesEatingCow** [comment]
I found an alternative. I know it is scanned but it seems to work very well. I checked my hero and attack on titan so far and they have the latest chapters avaliable. ![Screenshot_2020-08-19-12-36-09.png](https://user-images.githubusercontent.com/69094343/90664661-eeb2a900-e218-11ea-95a1-10bc47d58a59.png) https://play.google.com/store/apps/details?id=com.dev.wolf.translatedmanga

**Comment by Mitia99** [comment]
@LeavesEatingCow There are already many other french alternatives in tachiyomi extensions.Check multisources(CMS Reader,Madara...).But Japscan is still the best french manga database.

**Comment by CarlosEsco** [comment]
japscan has been removed
