### ISSUE TITLE
MyReadingManga - unable to download + some pages doesn't load

### ISSUE THREAD

**Issue by missimperfect** [inorichi/tachiyomi-extensions#577]
Tachiyomi ver: 0.8,0
MRM extension ver: 1.2.11

As at the previous closed issue that I've mentioned that I was unable to download the chapters from MRM since the pages doesn't load. And after I've downloaded the new extension, and have clear my cache, cookies, database I was still unable to download despite the chapters have fully loaded and the downloader was downloading all the pages it still shows 'error'.

![screenshot_2018-10-21-12-14-27](https://user-images.githubusercontent.com/40125698/47263050-59163780-d523-11e8-8ef0-d1ac8276adbc.png)
![screenshot_2018-10-21-12-14-37](https://user-images.githubusercontent.com/40125698/47263053-5ddaeb80-d523-11e8-869e-b04cc7cf2cb7.png)

This might happen to most of the manga.

And I found that there's 1 manga in my library where the 1st chapter doesn't load fully after the first 2 pages **(Title: Himono, Tokodoki, Shanairen'ai chapter 1)**

![screenshot_2018-10-21-12-17-12](https://user-images.githubusercontent.com/40125698/47263056-7b0fba00-d523-11e8-89e8-0453b14eb8ac.png)

and another one where the 1st chapter is "Page list is Empty". **(Title: Kanawanu Koi no Musubikata chapter 1)**

![screenshot_2018-10-21-12-17-21](https://user-images.githubusercontent.com/40125698/47263058-8367f500-d523-11e8-8155-84e54b621fb7.png)

Thank you and sorry for troubling you guys again.

**Comment by mll-Kerberos** [comment]
Thanks for providing screens and specific doujins to check, I'll look into it as soon as possible.

**Comment by mll-Kerberos** [comment]
@missimperfect The new update is ready, both issues have been solved, you can update the extension again and it should be working. Thanks for reporting the issue!

**Comment by missimperfect** [comment]
@mll-Kerberos Hii, thanks for solving my issues so quickly, but sorry to trouble you guys again. Apparently I'm still having this issue: "And I found that there's 1 manga in my library where the 1st chapter doesn't load fully after the first 2 pages **(Title: Himono, Tokodoki, Shanairen'ai chapter 1)**". If you guys don't mind is it possible if you guys look into this issue again? Thank you so much!!

**Comment by mll-Kerberos** [comment]
@missimperfect I've been looking and I fixed that problem in the newest version, you should be able to update now. If it's still not working, clear chapter cache (Settings -> Advanced -> Clear chapter cache) and it should work. Thanks for reporting!
