### ISSUE TITLE
ReadComicOnline (1.2.5) and Kissmanga and JapScan, mangadex etc. Anything with cloudflare

### ISSUE THREAD

**Issue by Fengr4saken** [inorichi/tachiyomi-extensions#894]
App Version: 0.8.0

Issue: "SyntaxError: parse error (line 1)" when loading catalogue or chapter. This affects all extensions.

Troubleshooting:
- restarted phone
- tested on different networks
- checked website is online
- checked for updates
- cleared cache and cookies in app settings
- cleared app cache on phone
- reinstalled app and extension 

Please note, I have no adblockers.

Thanks for your assistance in advance.

**Comment by leoboiko** [comment]
same here, I'm guessing site source changed?

**Comment by Generator** [comment]
Probably some site change, yesterday was working.

**Comment by Darkvramp** [comment]
Possible mitigation, while they figure out what is actually causing the issue, if you know how to use a program called cc cleaner, or are comfortable using saif program on your device, it is a known fix for this issue, but not for this specific catalogue. It was used in my case, to give me back access to the kiss manga catalogue. Please try and report here, if it works in this case because it would help the bug fixers in finding a work around while they find a solution.

**Comment by erik1844** [comment]
Sooo im using Tachiyomi and I have the exact same error "SyntaxError: parse error (line 1)"

**Comment by joseph-peace** [comment]
same here
if anyone has some sort of fix
please share

**Comment by Generator** [comment]
@joseph-peace not a fix, but an anternative, you can install My Manga Reader CMS extension, and use Read Comics Online catalog. However its not possible to migrate the source (there's a small diference on comics name).

**Comment by jayrthrush2** [comment]
Same issue. It was working around 7am EDT this morning, but not now. As a test, i installed Tachiyomi and the ReadComicsOnline extension on another device that never had it installed before, and still getting the same error.

**Comment by erik1844** [comment]
aw man some one halp us

**Comment by Fengr4saken** [comment]
I resolved to just use the actual readcomiconline.to website while I wait for the fix. I noticed their mobile site is broken and I just get the desktop site. So I assume some changes have happened.

**Comment by marquesjpf** [comment]
Readcomiconline still works well (and quite fast actually) on mmrcms, so you guys might want to check ot out.

**Comment by CarlosEsco** [comment]
@marquesjpf mmrcms is readcomicswebsite which is a different website

**Comment by omu009** [comment]
Same issue here. Hope they fix it soon

**Comment by thevectorguy** [comment]
I'm having the same issue tried everything already with no luck please resolve this as soon as possible

**Comment by GintokiXSakata** [comment]
Japscan is still saying "SyntaxError: parse error (line 1)", please someone do something about it, it's the only French source available on the app so.. please.

**Comment by DitFranXX** [comment]
This issue caused by Cloudflare Challenges Resolver which coded on main app.

It's already fixed in latest dev version

**Comment by Fengr4saken** [comment]
Can confirm. Installed Dev build and it's working. Look forward to the stable release. Thanks @DitFranXX

**Comment by GintokiXSakata** [comment]
I installed the dev build like you said @Fengr4saken and it says "HTTP error 503" now. It will never end....

**Comment by pseudophotographer** [comment]
Is there going to be a new realease today? I'm still havinh syntax error.
Sorry if i don't understamd much about the topic.

**Comment by MPThLee** [comment]
A Fix is landed to Tachiyomi Stable version as version 0.8.1, Please Update Tachiyomi to 0.8.1 for fix this problem.


Closed this issue, Please.

**Comment by Reiriin** [comment]
Downloaded the latest version of Tachiyomi, version 0.8.1. KissManga is loading now and downloading is also fine.

**Comment by GintokiXSakata** [comment]
Japscan is still isn't working with the latest version of Tachiyomi version 0.8.1.
