### ISSUE TITLE
ReadComicOnline/KissManga/MangaHasu: HTTP error 503/Duktape error

### ISSUE THREAD

**Issue by Radio-9** [inorichi/tachiyomi-extensions#951]
Unable to access extension ReadComicOnline, due to HTTP error 503
ReadComicOnline version: 1.2.5
https://readcomiconline.to/

Tried this in both Tachiyomi 0.8.1, Tachiyomi r1469

**Comment by leoteesh** [comment]
Also getting the same error for mangahasu

**Comment by QuietusWolfe** [comment]
Same error with Kissmanaga on 0.8.1

**Comment by TheWrightStuff1994** [comment]
Having same issue as well!

**Comment by Neshura87** [comment]
Same error on Kissmanga version 1.2.9 using Tachiyomi 0.8.1. Tried clearing cookies and opening kissmanga in the browser, reinstalling the extension and restarting my phone but did not work

**Comment by hXtreme** [comment]
Try installing the My Manga Reader CMS extension it should provide a source called "Read Comics Online" which I believe is the same source as "ReadComicOnline". While this is not a solution it should allow you to read your comics till someone patches it.

**Comment by CarlosEsco** [comment]
@hxtreme it's not. Just similar named

**Comment by Radio-9** [comment]
Actually 'Read Comics Online' and 'ReadComicOnline' are not same, plus many comics from the latter source are not in the former source.

**Comment by DitFranXX** [comment]
It's CloudFlare issue, They update JS Challenges again.

Everything with CF can cause a 503 error.

**Comment by ThomasCapella** [comment]
I'm getting this too. I just installed the latest version and it's doing this so updating won't fix it.

**Comment by pseudophotographer** [comment]
Having same issue, some days ago we had the syntax error but it got patched. Do we have any news about the http error?

**Comment by yasnil03** [comment]
Also the same with Mango: HTTP error 503

**Comment by CarlosEsco** [comment]
fixed in latest dev tachiyomi.  Hopefully stable released soon.

**Comment by Fokkusuteru** [comment]
Same issue. I downloaded both the dev and the stable versions. The same error seems to come for both on kissmanga. Other sources work fine

**Comment by buzmeg** [comment]
R1471 is still returning 503.  I am still seeing it on other sources too.

**Comment by MerradOklom** [comment]
@buzmeg which source? I tried with Kissmanga and it's working fine

**Comment by Fokkusuteru** [comment]
My kissmanga isn't working. Rest of all sources are working fine. Errors alswyas seem to be on kissmanga with me

**Comment by TheWrightStuff1994** [comment]
ReadComicOnline.to and Kissmanga are working for me, don't know why it isn't working for others?

**Comment by Dial-upMan** [comment]
Error has changed from a 503 error to a "com.squareup.duktape.DuktapeException: ReferenceError: identifier 'atob' undefined".  No clue if this is just me as well as if it's important either.

**Comment by El-Gavy** [comment]
@Dial-upMan same here using mangahasu.

**Comment by pseudophotographer** [comment]
Having the same error: "com.squareup.duktape.DuktapeException: ReferenceError: identifier 'atob' undefined".

**Comment by Neshura87** [comment]
Same new error: "com.squareup.duktape.DuktapeException: Reference Error: identifier 'atob' undefined" using Kissmanga as the source

**Comment by pawrawr** [comment]
Getting also the new same error. "com.squareup.duktape.DuktapeException: Reference Error: identifier 'atob' undefined" using Kissmanga as the source (using latest stable: 0.8.1 and Kissmanga 1.2.9)

**Comment by avgjoh** [comment]
Going directly to KissManga seems to get it stuck on the 5 second challenge, so the 'atob' issue may be a KissManga thing.
For those still getting the 503, did you clear your cookies in the app?

**Comment by joeoh1359** [comment]
On r1471:

Going directly to KissManga seems to get it stuck on the 5 second challenge, so the squareup.duktape 'atob' issue may be a KissManga thing.

For those still getting the 503, did you clear your cookies in the app?

EDIT:
Mangahasu seems to also fail with the 'atob' issue when trying to actually read anything.

EDITx2:
Seems like it's cloudflare again, since cloudflare's protection shows up for Mangahasu when you go into a chapter. Oddly enough mangahasu seems to work fine (in browser), but kissmanga is just straight up broken.

**Comment by ThomasCapella** [comment]
I'm using F-Droid. Will it update if I'm using the dev repository?

**Comment by reddeimon** [comment]
Same problem with version 0.8.1- r1471

**Comment by barracudaman** [comment]
I'm having the same issue.  I keep on getting "com.squareup.duktape.DuktapeException: ReferenceError: identifier 'atob' undefined" every time I attempt to open the ReadComicOnline (V 1.2.5) extension. I've tried to get it to work on both 0.8.1 and r1471. If you could patch this, it would be much appreciated.

**Comment by joeoh1359** [comment]
I'm no longer getting the atob error now (v0.8.1 r1471).
Wondering if it's because I switched networks or if it was on cloudflares end.

**Comment by barracudaman** [comment]
I'm no longer getting the atob error either. Instead, I am getting a 503 error.

**Comment by Peuuuur-Noel** [comment]
Duktape exception is an issue due to CloudFlare code changes that happens sometimes. They are maybe testing some changes. Troubles are gone for now, but can come back anytime.

I put this here in case it could be used.
Here are changes that I saw and break the CloudFlare interceptor in the base app (https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt).

- JS and DOM/HTML evaluation needed. Duktape Android can't handle this.
- New variable `k` with the ID to a hidden div with content than need to be eval (return an integer).
exemple: `t = t.substr(r.length); t = t.substr(0,t.length-1); k = 'cf-dn-zjAaF';`
- Obfuscated code does call to DOM like this:
`atob("ZG9jdW1l")+(undefined+"")[1]+(true+"")[0]+(+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+(false+[0]+String)[20]+(true+"")[3]+(true+"")[0]+"Element"+(+[]+Boolean)[10]+(NaN+[Infinity])[10]+"Id("+(+(20))["to"+String["name"]](21)+")."+atob("aW5uZXJIVE1M")`
We get this once eval:
`document.getElementById(k).innerHTML`
- Function `atob()` -> base64 decode. Not supported by the version of Duktape Android used?

**Comment by pawrawr** [comment]
No more atob error, 503 error is the thing that I got now.

**Comment by arkon** [comment]
Thanks for the info, @Peuuuur-Noel. 

> Function `atob()` -> base64 decode. Not supported by the version of Duktape Android used?

Makes sense. Duktape is an implementation of ECMAScript, and `atob()` is part of the browser `window` API.

**Comment by Neshura87** [comment]
Atob error gone 503 is back, hope next stable with the fix comes out soon

**Comment by pawrawr** [comment]
No more atob error, 503 error is the thing that I got now.

**Comment by DitFranXX** [comment]
Try latest dev build.

**Comment by yasnil03** [comment]
How?

**Comment by aqeeliz** [comment]
> How?

Try https://tachiyomi.kanade.eu/latest

**Comment by thomasprat49** [comment]
It's working for me with the latest dev

**Comment by El-Gavy** [comment]
Same here, r1474 solved it ! Thx guys!

**Comment by fatimagrace015** [comment]
hello, r1474 is not working on me. i tried reinstalling the app, clearing cache, reinstalling MangaHasu and restarting my phone but still cant download/read, always HTTP error 503

**Comment by Reiriin** [comment]
I tried r1474 and KissManga is still not working...

**Comment by rachzps** [comment]
presents the following error

SyntaxError:parse error line(1)
entension ver. 1.2.9 kissManga

**Comment by AedricVintera** [comment]
I tried r1474 on Thursday and it wasn't working at the time. Not sure what I was doing wrong or what might have changed but r1474 and KissManga extension are working for me as of right now.
Thanks!

**Comment by matryosha** [comment]
Is the patch going to stable?

**Comment by lenyer21** [comment]
Why is KissManga isn't functioning It says http error 503 ...what should I do plsss

**Comment by demir923** [comment]
I also have a http error 503 on Japscan (French source) even with the New update

**Comment by leoteesh** [comment]
Getting ducktape error on mangahasu after the new update. Same error with rev version

**Comment by CarlosEsco** [comment]
Cloudflare change again

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi/issues/1945
